name: Master Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Mona"
