name: A workflow to test actions/setup-python
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.7', 'pypy3' ]
    name: Python ${{ matrix.python }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: pip install django
      - run: python ./action-python/entry.py
