name: A workflow to test actions/setup-python
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        python: [ '3.7', 'pypy3' ]
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python }} build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: pip install django
      - run: python ./action-python/entry.py
